### PR TITLE
Move CleanRepo up a folder level

### PR DESCRIPTION
**Pull request by gewarren**

### CODE REVIEW

**Comment by IEvangelist** [comment]
Why does this need to move? I think it might cause issues with the `Dockerfile` and scoping of container context.

**Comment by gewarren** [comment]
> Why does this need to move? I think it might cause issues with the `Dockerfile` and scoping of container context.

There were two consecutive CleanRepo folders.

**Comment by IEvangelist** [comment]
You'll have to also update the workflows to correctly locate the project now.

See https://github.com/dotnet/docs-tools/actions/runs/9997562463/job/27634409992?pr=380

Also, every single consuming workflow will break - unless updated with this as well.

For example:

https://github.com/dotnet/docs-aspire/blob/main/.github/workflows/clean-repo.yml#L30

**Comment by gewarren** [comment]
The docs-verifier failure is a false positive - it think I need to add a redirect for the action.yml file that was moved.

**Comment by gewarren** [comment]
@IEvangelist Does this look okay?

**Pull request merged**
